FROM php:8.5-cli

# Expõe a porta
ENV PORT=10000
EXPOSE 10000

# Define o diretório de trabalho
WORKDIR /var/www/html

# Copia todos os arquivos
COPY . .

# Comando para rodar o servidor PHP com router.php
CMD ["sh", "-c", "php -S 0.0.0.0:$PORT router.php"]